[package]
authors = ["matthew-plusprogramming <matthewlinplusprogramming@gmail.com>"]
edition = "2018"
name = "guessing_game"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"
